# $HOME/.config/alacritty/alacritty.toml

[font]
size = 16
# builtin_box_drawing = true

[font.normal]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Medium"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Medium Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window]
decorations = "None"
opacity = 0.95
blur = true

[window.padding]
x = 25 
y = 25

[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
